// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:frosty_pine/adapters/presenters/models/brand_display_model.dart';
import 'package:frosty_pine/frb_generated.dart';

// Rust type: RustOpaqueMoi<Arc < dyn BrandRepository >>
abstract class ArcBrandRepository implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AddNewBrandUseCase>>
abstract class AddNewBrandUseCase implements RustOpaqueInterface {
  factory AddNewBrandUseCase({required ArcBrandRepository brandRepository, required ArcFlutterPresenter flutterPresenter}) => RustLib.instance.api
      .crateAdaptersTranslationsAddNewBrandUseCaseAddNewBrandUseCaseNew(brandRepository: brandRepository, flutterPresenter: flutterPresenter);
  Future<BrandDisplayModel> execute({required String name});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < FlutterPresenter >>>
abstract class ArcFlutterPresenter implements RustOpaqueInterface {}
