// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:frosty_pine/frb_generated.dart';

// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `execute`, `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AddNewBrandUseCaseWrapper>>
abstract class AddNewBrandUseCaseWrapper implements RustOpaqueInterface {
  ArcAddNewBrandUseCase get field0;

  set field0(ArcAddNewBrandUseCase field0);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < AddNewBrandUseCase >>>
abstract class ArcAddNewBrandUseCase implements RustOpaqueInterface {}
