// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:frosty_pine/adapters/translations/mirrors.dart';
import 'package:frosty_pine/frb_generated.dart';

// Rust type: RustOpaqueMoi<Arc < dyn BrandRepository >>
abstract class ArcBrandRepository implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AddNewBrandUseCaseError>>
abstract class AddNewBrandUseCaseError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AddNewBrandUseCaseWrapper>>
abstract class AddNewBrandUseCaseWrapper implements RustOpaqueInterface {
  Future<Brand> execute({required String name});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AddNewBrandUseCaseWrapper> newInstance({required ArcBrandRepository brandRepository}) =>
      RustLib.instance.api.crateAdaptersTranslationsAddNewBrandUseCaseWrapperAddNewBrandUseCaseWrapperNew(brandRepository: brandRepository);
}
