[package]
name = "in_memory_storage"
version = "0.1.0"
edition = "2024"

[dependencies]
expense_tracking = { path = "../expense_tracking" }
async-trait = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
uuid-b64 = { workspace = true }
