[package]
name = "cross-platform"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
expense_tracking = { path = "../expense_tracking" }
in_memory_storage = { path = "../in_memory_storage" }
tokio = { workspace = true }
flutter_rust_bridge = "=2.8.0"
