// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:frosy_pine/src/rust/application/ui/controllers/brand_controller.dart';
import 'package:frosy_pine/src/rust/frb_generated.dart';

Future<ArcBrandRepository> createBrandRepositoryInMemoryImpl({
  required List<Brand> initialData,
}) =>
    RustLib.instance.api.crateApplicationBaseCreateBrandRepositoryInMemoryImpl(
      initialData: initialData,
    );

Future<AddNewBrandUseCase> createInMemoryAddNewBrandUseCase({
  required ArcBrandRepository brandRepository,
}) => RustLib.instance.api.crateApplicationBaseCreateInMemoryAddNewBrandUseCase(
  brandRepository: brandRepository,
);

Future<RetrieveAllBrandsUseCase> createInMemoryRetrieveAllBrandsUseCase({
  required ArcBrandRepository brandRepository,
}) => RustLib.instance.api
    .crateApplicationBaseCreateInMemoryRetrieveAllBrandsUseCase(
      brandRepository: brandRepository,
    );

// Rust type: RustOpaqueMoi<Arc < dyn BrandRepository >>
abstract class ArcBrandRepository implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Brand>>
abstract class Brand implements RustOpaqueInterface {}
