// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:frosy_pine/src/rust/api/brand_controller.dart';
import 'package:frosy_pine/src/rust/frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcAddNewBrandUseCasePtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_ArcAddNewBrandUseCasePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcRetrieveAllBrandsUseCasePtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCasePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcBrandRepositoryPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepositoryPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BrandPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrandPtr;

  @protected
  Brand
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    dynamic raw,
  );

  @protected
  ArcAddNewBrandUseCase dco_decode_RustOpaque_ArcAddNewBrandUseCase(
    dynamic raw,
  );

  @protected
  ArcRetrieveAllBrandsUseCase dco_decode_RustOpaque_ArcRetrieveAllBrandsUseCase(
    dynamic raw,
  );

  @protected
  ArcBrandRepository dco_decode_RustOpaque_ArcdynBrandRepository(dynamic raw);

  @protected
  Brand
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BrandsController dco_decode_box_autoadd_brands_controller(dynamic raw);

  @protected
  BrandModel dco_decode_brand_model(dynamic raw);

  @protected
  BrandsController dco_decode_brands_controller(dynamic raw);

  @protected
  List<Brand>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    dynamic raw,
  );

  @protected
  List<BrandModel> dco_decode_list_brand_model(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Brand
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    SseDeserializer deserializer,
  );

  @protected
  ArcAddNewBrandUseCase sse_decode_RustOpaque_ArcAddNewBrandUseCase(
    SseDeserializer deserializer,
  );

  @protected
  ArcRetrieveAllBrandsUseCase sse_decode_RustOpaque_ArcRetrieveAllBrandsUseCase(
    SseDeserializer deserializer,
  );

  @protected
  ArcBrandRepository sse_decode_RustOpaque_ArcdynBrandRepository(
    SseDeserializer deserializer,
  );

  @protected
  Brand
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BrandsController sse_decode_box_autoadd_brands_controller(
    SseDeserializer deserializer,
  );

  @protected
  BrandModel sse_decode_brand_model(SseDeserializer deserializer);

  @protected
  BrandsController sse_decode_brands_controller(SseDeserializer deserializer);

  @protected
  List<Brand>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    SseDeserializer deserializer,
  );

  @protected
  List<BrandModel> sse_decode_list_brand_model(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    Brand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_ArcAddNewBrandUseCase(
    ArcAddNewBrandUseCase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_ArcRetrieveAllBrandsUseCase(
    ArcRetrieveAllBrandsUseCase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_ArcdynBrandRepository(
    ArcBrandRepository self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    Brand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_brands_controller(
    BrandsController self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_brand_model(BrandModel self, SseSerializer serializer);

  @protected
  void sse_encode_brands_controller(
    BrandsController self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    List<Brand> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_brand_model(
    List<BrandModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  void rust_arc_increment_strong_count_RustOpaque_ArcAddNewBrandUseCase(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_ArcAddNewBrandUseCase(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_ArcAddNewBrandUseCasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosy_pine_rust_arc_increment_strong_count_RustOpaque_ArcAddNewBrandUseCase',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_ArcAddNewBrandUseCase =
      _rust_arc_increment_strong_count_RustOpaque_ArcAddNewBrandUseCasePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_ArcAddNewBrandUseCase(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_ArcAddNewBrandUseCase(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_ArcAddNewBrandUseCasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosy_pine_rust_arc_decrement_strong_count_RustOpaque_ArcAddNewBrandUseCase',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_ArcAddNewBrandUseCase =
      _rust_arc_decrement_strong_count_RustOpaque_ArcAddNewBrandUseCasePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCase(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCase(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosy_pine_rust_arc_increment_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCase',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCase =
      _rust_arc_increment_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCasePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCase(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCase(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosy_pine_rust_arc_decrement_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCase',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCase =
      _rust_arc_decrement_strong_count_RustOpaque_ArcRetrieveAllBrandsUseCasePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepositoryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosy_pine_rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository =
      _rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepositoryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepositoryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosy_pine_rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository =
      _rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepositoryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrandPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosy_pine_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrandPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrandPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosy_pine_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrandPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
