// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:frosy_pine/src/rust/application/base.dart';
import 'package:frosy_pine/src/rust/application/ui/controllers/brand_controller.dart';
import 'package:frosy_pine/src/rust/application/ui/models/brand_model.dart';
import 'package:frosy_pine/src/rust/frb_generated.dart';
import 'package:frosy_pine/src/rust/frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  RustLib._();
  @internal
  static final instance = RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApplicationBaseInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.9.0';

  @override
  int get rustContentHash => 52583359;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_frosy_pine',
        ioDirectory: 'target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<BrandModel>
  crateApplicationUiControllersBrandControllerBrandsControllerAddNewBrand({
    required BrandsController that,
    required String name,
  });

  BrandsController
  crateApplicationUiControllersBrandControllerBrandsControllerNew({
    required AddNewBrandUseCase addNewBrandUseCase,
    required RetrieveAllBrandsUseCase retrieveAllBrandsUseCase,
  });

  Future<List<BrandModel>>
  crateApplicationUiControllersBrandControllerBrandsControllerRetrieveAllBrands({
    required BrandsController that,
  });

  Future<ArcBrandRepository>
  crateApplicationBaseCreateBrandRepositoryInMemoryImpl({
    required List<Brand> initialData,
  });

  Future<AddNewBrandUseCase>
  crateApplicationBaseCreateInMemoryAddNewBrandUseCase({
    required ArcBrandRepository brandRepository,
  });

  Future<RetrieveAllBrandsUseCase>
  crateApplicationBaseCreateInMemoryRetrieveAllBrandsUseCase({
    required ArcBrandRepository brandRepository,
  });

  Future<void> crateApplicationBaseInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AddNewBrandUseCase;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AddNewBrandUseCase;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AddNewBrandUseCasePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcBrandRepository;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcBrandRepository;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcBrandRepositoryPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RetrieveAllBrandsUseCase;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RetrieveAllBrandsUseCase;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RetrieveAllBrandsUseCasePtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Brand;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Brand;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BrandPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BrandModel>
  crateApplicationUiControllersBrandControllerBrandsControllerAddNewBrand({
    required BrandsController that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_brands_controller(that, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_brand_model,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApplicationUiControllersBrandControllerBrandsControllerAddNewBrandConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApplicationUiControllersBrandControllerBrandsControllerAddNewBrandConstMeta =>
      const TaskConstMeta(
        debugName: 'brands_controller_add_new_brand',
        argNames: ['that', 'name'],
      );

  @override
  BrandsController
  crateApplicationUiControllersBrandControllerBrandsControllerNew({
    required AddNewBrandUseCase addNewBrandUseCase,
    required RetrieveAllBrandsUseCase retrieveAllBrandsUseCase,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_AddNewBrandUseCase(
            addNewBrandUseCase,
            serializer,
          );
          sse_encode_RustOpaque_RetrieveAllBrandsUseCase(
            retrieveAllBrandsUseCase,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_brands_controller,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApplicationUiControllersBrandControllerBrandsControllerNewConstMeta,
        argValues: [addNewBrandUseCase, retrieveAllBrandsUseCase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApplicationUiControllersBrandControllerBrandsControllerNewConstMeta =>
      const TaskConstMeta(
        debugName: 'brands_controller_new',
        argNames: ['addNewBrandUseCase', 'retrieveAllBrandsUseCase'],
      );

  @override
  Future<List<BrandModel>>
  crateApplicationUiControllersBrandControllerBrandsControllerRetrieveAllBrands({
    required BrandsController that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_brands_controller(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_brand_model,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApplicationUiControllersBrandControllerBrandsControllerRetrieveAllBrandsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApplicationUiControllersBrandControllerBrandsControllerRetrieveAllBrandsConstMeta =>
      const TaskConstMeta(
        debugName: 'brands_controller_retrieve_all_brands',
        argNames: ['that'],
      );

  @override
  Future<ArcBrandRepository>
  crateApplicationBaseCreateBrandRepositoryInMemoryImpl({
    required List<Brand> initialData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
            initialData,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_RustOpaque_ArcdynBrandRepository,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApplicationBaseCreateBrandRepositoryInMemoryImplConstMeta,
        argValues: [initialData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApplicationBaseCreateBrandRepositoryInMemoryImplConstMeta =>
      const TaskConstMeta(
        debugName: 'create_brand_repository_in_memory_impl',
        argNames: ['initialData'],
      );

  @override
  Future<AddNewBrandUseCase>
  crateApplicationBaseCreateInMemoryAddNewBrandUseCase({
    required ArcBrandRepository brandRepository,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_ArcdynBrandRepository(
            brandRepository,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_RustOpaque_AddNewBrandUseCase,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApplicationBaseCreateInMemoryAddNewBrandUseCaseConstMeta,
        argValues: [brandRepository],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApplicationBaseCreateInMemoryAddNewBrandUseCaseConstMeta =>
      const TaskConstMeta(
        debugName: 'create_in_memory_add_new_brand_use_case',
        argNames: ['brandRepository'],
      );

  @override
  Future<RetrieveAllBrandsUseCase>
  crateApplicationBaseCreateInMemoryRetrieveAllBrandsUseCase({
    required ArcBrandRepository brandRepository,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_ArcdynBrandRepository(
            brandRepository,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_RustOpaque_RetrieveAllBrandsUseCase,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApplicationBaseCreateInMemoryRetrieveAllBrandsUseCaseConstMeta,
        argValues: [brandRepository],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApplicationBaseCreateInMemoryRetrieveAllBrandsUseCaseConstMeta =>
      const TaskConstMeta(
        debugName: 'create_in_memory_retrieve_all_brands_use_case',
        argNames: ['brandRepository'],
      );

  @override
  Future<void> crateApplicationBaseInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApplicationBaseInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApplicationBaseInitAppConstMeta =>
      const TaskConstMeta(debugName: 'init_app', argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AddNewBrandUseCase =>
      wire.rust_arc_increment_strong_count_RustOpaque_AddNewBrandUseCase;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AddNewBrandUseCase =>
      wire.rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCase;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcBrandRepository =>
      wire.rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcBrandRepository =>
      wire.rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RetrieveAllBrandsUseCase =>
      wire.rust_arc_increment_strong_count_RustOpaque_RetrieveAllBrandsUseCase;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RetrieveAllBrandsUseCase =>
      wire.rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCase;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Brand =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Brand =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand;

  @protected
  Brand
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BrandImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AddNewBrandUseCase dco_decode_RustOpaque_AddNewBrandUseCase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AddNewBrandUseCaseImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcBrandRepository dco_decode_RustOpaque_ArcdynBrandRepository(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcBrandRepositoryImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RetrieveAllBrandsUseCase dco_decode_RustOpaque_RetrieveAllBrandsUseCase(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RetrieveAllBrandsUseCaseImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  Brand
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BrandImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BrandsController dco_decode_box_autoadd_brands_controller(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_brands_controller(raw);
  }

  @protected
  BrandModel dco_decode_brand_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return BrandModel(name: dco_decode_String(arr[0]));
  }

  @protected
  BrandsController dco_decode_brands_controller(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BrandsController.raw(
      addNewBrandUseCase: dco_decode_RustOpaque_AddNewBrandUseCase(arr[0]),
      retrieveAllBrandsUseCase: dco_decode_RustOpaque_RetrieveAllBrandsUseCase(
        arr[1],
      ),
    );
  }

  @protected
  List<Brand>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
          dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand,
        )
        .toList();
  }

  @protected
  List<BrandModel> dco_decode_list_brand_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_brand_model).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Brand
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BrandImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AddNewBrandUseCase sse_decode_RustOpaque_AddNewBrandUseCase(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AddNewBrandUseCaseImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcBrandRepository sse_decode_RustOpaque_ArcdynBrandRepository(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcBrandRepositoryImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RetrieveAllBrandsUseCase sse_decode_RustOpaque_RetrieveAllBrandsUseCase(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RetrieveAllBrandsUseCaseImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Brand
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BrandImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BrandsController sse_decode_box_autoadd_brands_controller(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return sse_decode_brands_controller(deserializer);
  }

  @protected
  BrandModel sse_decode_brand_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_name = sse_decode_String(deserializer);
    return BrandModel(name: var_name);
  }

  @protected
  BrandsController sse_decode_brands_controller(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_addNewBrandUseCase = sse_decode_RustOpaque_AddNewBrandUseCase(
      deserializer,
    );
    final var_retrieveAllBrandsUseCase =
        sse_decode_RustOpaque_RetrieveAllBrandsUseCase(deserializer);
    return BrandsController.raw(
      addNewBrandUseCase: var_addNewBrandUseCase,
      retrieveAllBrandsUseCase: var_retrieveAllBrandsUseCase,
    );
  }

  @protected
  List<Brand>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <Brand>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  List<BrandModel> sse_decode_list_brand_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <BrandModel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_brand_model(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    Brand self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BrandImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_AddNewBrandUseCase(
    AddNewBrandUseCase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AddNewBrandUseCaseImpl).frbInternalSseEncode(),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_ArcdynBrandRepository(
    ArcBrandRepository self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcBrandRepositoryImpl).frbInternalSseEncode(),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_RetrieveAllBrandsUseCase(
    RetrieveAllBrandsUseCase self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RetrieveAllBrandsUseCaseImpl).frbInternalSseEncode(),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    Brand self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as BrandImpl).frbInternalSseEncode(), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_brands_controller(
    BrandsController self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_brands_controller(self, serializer);
  }

  @protected
  void sse_encode_brand_model(BrandModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_brands_controller(
    BrandsController self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_RustOpaque_AddNewBrandUseCase(
      self.addNewBrandUseCase,
      serializer,
    );
    sse_encode_RustOpaque_RetrieveAllBrandsUseCase(
      self.retrieveAllBrandsUseCase,
      serializer,
    );
  }

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
    List<Brand> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(
        item,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_list_brand_model(
    List<BrandModel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_brand_model(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class AddNewBrandUseCaseImpl extends RustOpaque implements AddNewBrandUseCase {
  // Not to be used by end users
  AddNewBrandUseCaseImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AddNewBrandUseCaseImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AddNewBrandUseCase,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AddNewBrandUseCase,
    rustArcDecrementStrongCountPtr:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_AddNewBrandUseCasePtr,
  );
}

@sealed
class ArcBrandRepositoryImpl extends RustOpaque implements ArcBrandRepository {
  // Not to be used by end users
  ArcBrandRepositoryImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcBrandRepositoryImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ArcBrandRepository,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ArcBrandRepository,
    rustArcDecrementStrongCountPtr:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_ArcBrandRepositoryPtr,
  );
}

@sealed
class BrandImpl extends RustOpaque implements Brand {
  // Not to be used by end users
  BrandImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BrandImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Brand,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Brand,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_BrandPtr,
  );
}

@sealed
class RetrieveAllBrandsUseCaseImpl extends RustOpaque
    implements RetrieveAllBrandsUseCase {
  // Not to be used by end users
  RetrieveAllBrandsUseCaseImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RetrieveAllBrandsUseCaseImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib
            .instance
            .api
            .rust_arc_increment_strong_count_RetrieveAllBrandsUseCase,
    rustArcDecrementStrongCount:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_RetrieveAllBrandsUseCase,
    rustArcDecrementStrongCountPtr:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_RetrieveAllBrandsUseCasePtr,
  );
}
