// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:frosty_pine/src/rust/frb_generated.dart';

// Rust type: RustOpaqueMoi<AddNewBrandUseCase>
abstract class AddNewBrandUseCase implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<RetrieveAllBrandsUseCase>
abstract class RetrieveAllBrandsUseCase implements RustOpaqueInterface {}
