// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:frosy_pine/src/rust/api/models.dart';
import 'package:frosy_pine/src/rust/frb_generated.dart';

Future<BrandModel> addNewBrand({required String name}) =>
    RustLib.instance.api.crateApiBrandControllerAddNewBrand(name: name);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AddNewBrandUseCaseError>>
abstract class AddNewBrandUseCaseError implements RustOpaqueInterface {}
