// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:frosy_pine/src/rust/frb_generated.dart';
import 'package:frosy_pine/src/rust/lib.dart';

Future<BoxBrandRepository> createBrandRepositoryInMemoryImpl({
  required Map<String, Brand> data,
}) => RustLib.instance.api.crateApiInitCreateBrandRepositoryInMemoryImpl(
  data: data,
);

Future<AddNewBrandUseCase> createAddNewBrandUseCase({
  required BoxBrandRepository brandRepository,
}) => RustLib.instance.api.crateApiInitCreateAddNewBrandUseCase(
  brandRepository: brandRepository,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn BrandRepository + Sync + Send >>>
abstract class BoxBrandRepository implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Brand>>
abstract class Brand implements RustOpaqueInterface {}
