// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:frosty_pine/adapters/models/brand_display_model.dart';
import 'package:frosty_pine/adapters/presenters/brand_presenter.dart';
import 'package:frosty_pine/adapters/rust/init.dart';
import 'package:frosty_pine/frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({required super.handler, required super.wire, required super.generalizedFrbRustBinding, required super.portManager});

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AddNewBrandUseCasePtr => wire.rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCase;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ArcBrandRepositoryPtr => wire.rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RetrieveAllBrandsUseCasePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCase;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BrandPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand;

  @protected
  Brand dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(dynamic raw);

  @protected
  AddNewBrandUseCase dco_decode_RustOpaque_AddNewBrandUseCase(dynamic raw);

  @protected
  ArcBrandRepository dco_decode_RustOpaque_ArcdynBrandRepository(dynamic raw);

  @protected
  RetrieveAllBrandsUseCase dco_decode_RustOpaque_RetrieveAllBrandsUseCase(dynamic raw);

  @protected
  Brand dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BrandPresenter dco_decode_box_autoadd_brand_presenter(dynamic raw);

  @protected
  BrandDisplayModel dco_decode_brand_display_model(dynamic raw);

  @protected
  BrandPresenter dco_decode_brand_presenter(dynamic raw);

  @protected
  List<Brand> dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(dynamic raw);

  @protected
  List<BrandDisplayModel> dco_decode_list_brand_display_model(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Brand sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(SseDeserializer deserializer);

  @protected
  AddNewBrandUseCase sse_decode_RustOpaque_AddNewBrandUseCase(SseDeserializer deserializer);

  @protected
  ArcBrandRepository sse_decode_RustOpaque_ArcdynBrandRepository(SseDeserializer deserializer);

  @protected
  RetrieveAllBrandsUseCase sse_decode_RustOpaque_RetrieveAllBrandsUseCase(SseDeserializer deserializer);

  @protected
  Brand sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BrandPresenter sse_decode_box_autoadd_brand_presenter(SseDeserializer deserializer);

  @protected
  BrandDisplayModel sse_decode_brand_display_model(SseDeserializer deserializer);

  @protected
  BrandPresenter sse_decode_brand_presenter(SseDeserializer deserializer);

  @protected
  List<Brand> sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(SseDeserializer deserializer);

  @protected
  List<BrandDisplayModel> sse_decode_list_brand_display_model(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(Brand self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_AddNewBrandUseCase(AddNewBrandUseCase self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_ArcdynBrandRepository(ArcBrandRepository self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_RetrieveAllBrandsUseCase(RetrieveAllBrandsUseCase self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(Brand self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_brand_presenter(BrandPresenter self, SseSerializer serializer);

  @protected
  void sse_encode_brand_display_model(BrandDisplayModel self, SseSerializer serializer);

  @protected
  void sse_encode_brand_presenter(BrandPresenter self, SseSerializer serializer);

  @protected
  void sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(List<Brand> self, SseSerializer serializer);

  @protected
  void sse_encode_list_brand_display_model(List<BrandDisplayModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary();

  void rust_arc_increment_strong_count_RustOpaque_AddNewBrandUseCase(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_AddNewBrandUseCase(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCase(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCase(ptr);

  void rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository(ptr);

  void rust_arc_increment_strong_count_RustOpaque_RetrieveAllBrandsUseCase(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_RetrieveAllBrandsUseCase(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCase(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCase(ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void rust_arc_increment_strong_count_RustOpaque_AddNewBrandUseCase(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCase(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_RetrieveAllBrandsUseCase(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCase(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBrand(int ptr);
}
