// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:frosty_pine/adapters/presenters/flutter_presenter.dart';
import 'package:frosty_pine/adapters/presenters/models/brand_display_model.dart';
import 'package:frosty_pine/adapters/translations/add_new_brand_use_case_wrapper.dart';
import 'package:frosty_pine/adapters/translations/mirrors.dart';
import 'package:frosty_pine/adapters/translations/rust_factory.dart';
import 'package:frosty_pine/frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({required super.handler, required super.wire, required super.generalizedFrbRustBinding, required super.portManager});

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AddNewBrandUseCasePtr => wire._rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCasePtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ArcBrandRepositoryPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepositoryPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RetrieveAllBrandsUseCasePtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCasePtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AddNewBrandUseCaseErrorPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseErrorPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AddNewBrandUseCaseWrapperPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapperPtr;

  @protected
  AddNewBrandUseCaseError dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError(dynamic raw);

  @protected
  AddNewBrandUseCaseWrapper dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(dynamic raw);

  @protected
  AddNewBrandUseCaseWrapper dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(dynamic raw);

  @protected
  AddNewBrandUseCase dco_decode_RustOpaque_AddNewBrandUseCase(dynamic raw);

  @protected
  ArcBrandRepository dco_decode_RustOpaque_ArcdynBrandRepository(dynamic raw);

  @protected
  RetrieveAllBrandsUseCase dco_decode_RustOpaque_RetrieveAllBrandsUseCase(dynamic raw);

  @protected
  AddNewBrandUseCaseError dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError(dynamic raw);

  @protected
  AddNewBrandUseCaseWrapper dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BrandFlutterPresenter dco_decode_box_autoadd_brand_flutter_presenter(dynamic raw);

  @protected
  Brand dco_decode_brand(dynamic raw);

  @protected
  BrandDisplayModel dco_decode_brand_display_model(dynamic raw);

  @protected
  BrandFlutterPresenter dco_decode_brand_flutter_presenter(dynamic raw);

  @protected
  List<Brand> dco_decode_list_brand(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  RustFactory dco_decode_rust_factory(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AddNewBrandUseCaseError sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError(
    SseDeserializer deserializer,
  );

  @protected
  AddNewBrandUseCaseWrapper sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(
    SseDeserializer deserializer,
  );

  @protected
  AddNewBrandUseCaseWrapper sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(
    SseDeserializer deserializer,
  );

  @protected
  AddNewBrandUseCase sse_decode_RustOpaque_AddNewBrandUseCase(SseDeserializer deserializer);

  @protected
  ArcBrandRepository sse_decode_RustOpaque_ArcdynBrandRepository(SseDeserializer deserializer);

  @protected
  RetrieveAllBrandsUseCase sse_decode_RustOpaque_RetrieveAllBrandsUseCase(SseDeserializer deserializer);

  @protected
  AddNewBrandUseCaseError sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError(SseDeserializer deserializer);

  @protected
  AddNewBrandUseCaseWrapper sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BrandFlutterPresenter sse_decode_box_autoadd_brand_flutter_presenter(SseDeserializer deserializer);

  @protected
  Brand sse_decode_brand(SseDeserializer deserializer);

  @protected
  BrandDisplayModel sse_decode_brand_display_model(SseDeserializer deserializer);

  @protected
  BrandFlutterPresenter sse_decode_brand_flutter_presenter(SseDeserializer deserializer);

  @protected
  List<Brand> sse_decode_list_brand(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  RustFactory sse_decode_rust_factory(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError(
    AddNewBrandUseCaseError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(
    AddNewBrandUseCaseWrapper self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(
    AddNewBrandUseCaseWrapper self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_AddNewBrandUseCase(AddNewBrandUseCase self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_ArcdynBrandRepository(ArcBrandRepository self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_RetrieveAllBrandsUseCase(RetrieveAllBrandsUseCase self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError(AddNewBrandUseCaseError self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(
    AddNewBrandUseCaseWrapper self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_brand_flutter_presenter(BrandFlutterPresenter self, SseSerializer serializer);

  @protected
  void sse_encode_brand(Brand self, SseSerializer serializer);

  @protected
  void sse_encode_brand_display_model(BrandDisplayModel self, SseSerializer serializer);

  @protected
  void sse_encode_brand_flutter_presenter(BrandFlutterPresenter self, SseSerializer serializer);

  @protected
  void sse_encode_list_brand(List<Brand> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_rust_factory(RustFactory self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) => RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  void rust_arc_increment_strong_count_RustOpaque_AddNewBrandUseCase(ffi.Pointer<ffi.Void> ptr) {
    return _rust_arc_increment_strong_count_RustOpaque_AddNewBrandUseCase(ptr);
  }

  late final _rust_arc_increment_strong_count_RustOpaque_AddNewBrandUseCasePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_frosty_pine_rust_arc_increment_strong_count_RustOpaque_AddNewBrandUseCase',
  );
  late final _rust_arc_increment_strong_count_RustOpaque_AddNewBrandUseCase =
      _rust_arc_increment_strong_count_RustOpaque_AddNewBrandUseCasePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCase(ffi.Pointer<ffi.Void> ptr) {
    return _rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCase(ptr);
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCasePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_frosty_pine_rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCase',
  );
  late final _rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCase =
      _rust_arc_decrement_strong_count_RustOpaque_AddNewBrandUseCasePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository(ffi.Pointer<ffi.Void> ptr) {
    return _rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository(ptr);
  }

  late final _rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepositoryPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_frosty_pine_rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository',
  );
  late final _rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepository =
      _rust_arc_increment_strong_count_RustOpaque_ArcdynBrandRepositoryPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository(ffi.Pointer<ffi.Void> ptr) {
    return _rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository(ptr);
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepositoryPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_frosty_pine_rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository',
  );
  late final _rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepository =
      _rust_arc_decrement_strong_count_RustOpaque_ArcdynBrandRepositoryPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_RetrieveAllBrandsUseCase(ffi.Pointer<ffi.Void> ptr) {
    return _rust_arc_increment_strong_count_RustOpaque_RetrieveAllBrandsUseCase(ptr);
  }

  late final _rust_arc_increment_strong_count_RustOpaque_RetrieveAllBrandsUseCasePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_frosty_pine_rust_arc_increment_strong_count_RustOpaque_RetrieveAllBrandsUseCase',
  );
  late final _rust_arc_increment_strong_count_RustOpaque_RetrieveAllBrandsUseCase =
      _rust_arc_increment_strong_count_RustOpaque_RetrieveAllBrandsUseCasePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCase(ffi.Pointer<ffi.Void> ptr) {
    return _rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCase(ptr);
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCasePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
    'frbgen_frosty_pine_rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCase',
  );
  late final _rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCase =
      _rust_arc_decrement_strong_count_RustOpaque_RetrieveAllBrandsUseCasePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError(ffi.Pointer<ffi.Void> ptr) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError(ptr);
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosty_pine_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError(ffi.Pointer<ffi.Void> ptr) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError(ptr);
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosty_pine_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(ffi.Pointer<ffi.Void> ptr) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(ptr);
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapperPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosty_pine_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapperPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(ffi.Pointer<ffi.Void> ptr) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper(ptr);
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapperPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_frosty_pine_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapper =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAddNewBrandUseCaseWrapperPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
