// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:frosty_pine/frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `apply`

class FlutterPresenter {
  factory FlutterPresenter() => RustLib.instance.api.crateAdaptersPresentersFlutterPresenterFlutterPresenterNew();

  const FlutterPresenter.raw();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) => identical(this, other) || other is FlutterPresenter && runtimeType == other.runtimeType;
}
