// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_application/src/presentation/glue/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<StoreModel>> retrieveAvailableStores() =>
    RustLib.instance.api.crateApiStoreRetrieveAvailableStores();

class StoreModel {
  const StoreModel({required this.id, required this.name});
  final String id;
  final String name;

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<StoreModel> newInstance({
    required String id,
    required String name,
  }) => RustLib.instance.api.crateApiStoreStoreModelNew(id: id, name: name);

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
