// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:frosty_pine/frb_generated.dart';

class Brand {
  const Brand({required this.name});
  final String name;

  @override
  int get hashCode => name.hashCode;

  @override
  bool operator ==(Object other) => identical(this, other) || other is Brand && runtimeType == other.runtimeType && name == other.name;
}
